name: ghostwriter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ghostwriter:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test
        run: make test
      - name: Package
        run: make package
