# # For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# # https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# on:
#   push:
#     branches:
#       - main
#       - develop
#   pull_request:
#     branches:
#       - main
#       - develop

# name: R-CMD-check

# jobs:
#   R-CMD-check:
    
#     name: ${{ matrix.config.os }} (r-${{ matrix.config.r }})

#     runs-on: ${{ matrix.config.os }}

#     strategy:
#       matrix:
#         config:
#           - {os: ubuntu-latest, r: 'devel'}
#           - {os: ubuntu-latest, r: 'release'}
#           - {os: ubuntu-latest, r: 'oldrelease'}
#           - {os: macos-latest, r: 'devel'}
#           - {os: macos-latest, r: 'release'}
#           - {os: macos-latest, r: 'oldrelease'}
#           - {os: windows-latest, r: 'devel'}
#           - {os: windows-latest, r: 'release'}
#           - {os: windows-latest, r: 'oldrelease'}

#     steps:
#       - uses: actions/checkout@v2
#       - uses: r-lib/actions/setup-r@v1
#       - name: Install dependencies
#         run: |
#           install.packages(c("remotes", "rcmdcheck"))
#           remotes::install_deps(dependencies = TRUE)
#         shell: Rscript {0}
#       - name: Check
#         run: |
#           options(crayon.enabled = TRUE)
#           rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "error")
#         shell: Rscript {0}
